# Generated by Django 3.2.4 on 2021-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='customer.MenuItem'),
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=7),
        ),
    ]
